/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopsRouteImport } from './routes/shops'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopsIdRouteImport } from './routes/shops.$id'
import { Route as ListingsIdRouteImport } from './routes/listings.$id'
import { Route as AuthConfirmedRouteImport } from './routes/auth.confirmed'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPostAdRouteImport } from './routes/_authenticated/post-ad'
import { Route as AuthenticatedMyShopRouteImport } from './routes/_authenticated/my-shop'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedFavoritesRouteImport } from './routes/_authenticated/favorites'
import { Route as AuthenticatedInboxIdRouteImport } from './routes/_authenticated/inbox.$id'
import { Route as AuthenticatedEditListingIdRouteImport } from './routes/_authenticated/edit-listing.$id'

const ShopsRoute = ShopsRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsIdRoute = ShopsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ShopsRoute,
} as any)
const ListingsIdRoute = ListingsIdRouteImport.update({
  id: '/listings/$id',
  path: '/listings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmedRoute = AuthConfirmedRouteImport.update({
  id: '/confirmed',
  path: '/confirmed',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPostAdRoute = AuthenticatedPostAdRouteImport.update({
  id: '/post-ad',
  path: '/post-ad',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMyShopRoute = AuthenticatedMyShopRouteImport.update({
  id: '/my-shop',
  path: '/my-shop',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFavoritesRoute = AuthenticatedFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInboxIdRoute = AuthenticatedInboxIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedInboxRoute,
} as any)
const AuthenticatedEditListingIdRoute =
  AuthenticatedEditListingIdRouteImport.update({
    id: '/edit-listing/$id',
    path: '/edit-listing/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/browse': typeof BrowseRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shops': typeof ShopsRouteWithChildren
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/inbox': typeof AuthenticatedInboxRouteWithChildren
  '/my-shop': typeof AuthenticatedMyShopRoute
  '/post-ad': typeof AuthenticatedPostAdRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/auth/confirmed': typeof AuthConfirmedRoute
  '/listings/$id': typeof ListingsIdRoute
  '/shops/$id': typeof ShopsIdRoute
  '/edit-listing/$id': typeof AuthenticatedEditListingIdRoute
  '/inbox/$id': typeof AuthenticatedInboxIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/browse': typeof BrowseRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shops': typeof ShopsRouteWithChildren
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/inbox': typeof AuthenticatedInboxRouteWithChildren
  '/my-shop': typeof AuthenticatedMyShopRoute
  '/post-ad': typeof AuthenticatedPostAdRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/auth/confirmed': typeof AuthConfirmedRoute
  '/listings/$id': typeof ListingsIdRoute
  '/shops/$id': typeof ShopsIdRoute
  '/edit-listing/$id': typeof AuthenticatedEditListingIdRoute
  '/inbox/$id': typeof AuthenticatedInboxIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/browse': typeof BrowseRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shops': typeof ShopsRouteWithChildren
  '/_authenticated/favorites': typeof AuthenticatedFavoritesRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRouteWithChildren
  '/_authenticated/my-shop': typeof AuthenticatedMyShopRoute
  '/_authenticated/post-ad': typeof AuthenticatedPostAdRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/auth/confirmed': typeof AuthConfirmedRoute
  '/listings/$id': typeof ListingsIdRoute
  '/shops/$id': typeof ShopsIdRoute
  '/_authenticated/edit-listing/$id': typeof AuthenticatedEditListingIdRoute
  '/_authenticated/inbox/$id': typeof AuthenticatedInboxIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/browse'
    | '/forgot-password'
    | '/reset-password'
    | '/shops'
    | '/favorites'
    | '/inbox'
    | '/my-shop'
    | '/post-ad'
    | '/profile'
    | '/auth/confirmed'
    | '/listings/$id'
    | '/shops/$id'
    | '/edit-listing/$id'
    | '/inbox/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/browse'
    | '/forgot-password'
    | '/reset-password'
    | '/shops'
    | '/favorites'
    | '/inbox'
    | '/my-shop'
    | '/post-ad'
    | '/profile'
    | '/auth/confirmed'
    | '/listings/$id'
    | '/shops/$id'
    | '/edit-listing/$id'
    | '/inbox/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/browse'
    | '/forgot-password'
    | '/reset-password'
    | '/shops'
    | '/_authenticated/favorites'
    | '/_authenticated/inbox'
    | '/_authenticated/my-shop'
    | '/_authenticated/post-ad'
    | '/_authenticated/profile'
    | '/auth/confirmed'
    | '/listings/$id'
    | '/shops/$id'
    | '/_authenticated/edit-listing/$id'
    | '/_authenticated/inbox/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  BrowseRoute: typeof BrowseRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ShopsRoute: typeof ShopsRouteWithChildren
  ListingsIdRoute: typeof ListingsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shops': {
      id: '/shops'
      path: '/shops'
      fullPath: '/shops'
      preLoaderRoute: typeof ShopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$id': {
      id: '/shops/$id'
      path: '/$id'
      fullPath: '/shops/$id'
      preLoaderRoute: typeof ShopsIdRouteImport
      parentRoute: typeof ShopsRoute
    }
    '/listings/$id': {
      id: '/listings/$id'
      path: '/listings/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof ListingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirmed': {
      id: '/auth/confirmed'
      path: '/confirmed'
      fullPath: '/auth/confirmed'
      preLoaderRoute: typeof AuthConfirmedRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/post-ad': {
      id: '/_authenticated/post-ad'
      path: '/post-ad'
      fullPath: '/post-ad'
      preLoaderRoute: typeof AuthenticatedPostAdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-shop': {
      id: '/_authenticated/my-shop'
      path: '/my-shop'
      fullPath: '/my-shop'
      preLoaderRoute: typeof AuthenticatedMyShopRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/favorites': {
      id: '/_authenticated/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AuthenticatedFavoritesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inbox/$id': {
      id: '/_authenticated/inbox/$id'
      path: '/$id'
      fullPath: '/inbox/$id'
      preLoaderRoute: typeof AuthenticatedInboxIdRouteImport
      parentRoute: typeof AuthenticatedInboxRoute
    }
    '/_authenticated/edit-listing/$id': {
      id: '/_authenticated/edit-listing/$id'
      path: '/edit-listing/$id'
      fullPath: '/edit-listing/$id'
      preLoaderRoute: typeof AuthenticatedEditListingIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedInboxRouteChildren {
  AuthenticatedInboxIdRoute: typeof AuthenticatedInboxIdRoute
}

const AuthenticatedInboxRouteChildren: AuthenticatedInboxRouteChildren = {
  AuthenticatedInboxIdRoute: AuthenticatedInboxIdRoute,
}

const AuthenticatedInboxRouteWithChildren =
  AuthenticatedInboxRoute._addFileChildren(AuthenticatedInboxRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedFavoritesRoute: typeof AuthenticatedFavoritesRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRouteWithChildren
  AuthenticatedMyShopRoute: typeof AuthenticatedMyShopRoute
  AuthenticatedPostAdRoute: typeof AuthenticatedPostAdRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedEditListingIdRoute: typeof AuthenticatedEditListingIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedFavoritesRoute: AuthenticatedFavoritesRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRouteWithChildren,
  AuthenticatedMyShopRoute: AuthenticatedMyShopRoute,
  AuthenticatedPostAdRoute: AuthenticatedPostAdRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedEditListingIdRoute: AuthenticatedEditListingIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AuthRouteChildren {
  AuthConfirmedRoute: typeof AuthConfirmedRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthConfirmedRoute: AuthConfirmedRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ShopsRouteChildren {
  ShopsIdRoute: typeof ShopsIdRoute
}

const ShopsRouteChildren: ShopsRouteChildren = {
  ShopsIdRoute: ShopsIdRoute,
}

const ShopsRouteWithChildren = ShopsRoute._addFileChildren(ShopsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  BrowseRoute: BrowseRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ShopsRoute: ShopsRouteWithChildren,
  ListingsIdRoute: ListingsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
